### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by opichals** [espruino/Espruino#1062]
# UDP Support

The purpose of this ticket is to track Espruino native UDP support.
The intention is to loosely follow the node.js `dgram` (https://nodejs.org/api/dgram.html) module API .

The development is currently in progress and can be reviewed at https://github.com/espruino/Espruino/compare/master...opichals:espruino-udp

## Phase 1

Minimal effort to get UDP working.

- [x] Introduce ST_UDP flag
- [x] Drop NetCreateFlags in favor of SocketType
- [x] Add SocketType argument to net->createsocket()
- [x] Implement ST_UDP handling (network_linux.c)
- [x] Validate feasibility for ESP8266 (network_esp8266.c)
- [x] Validate this being enough for JS mDNS implementation
- [x] Multicast support
- [x] Made 'on:message' the same as 'on:data' (node.js compat)

```js
// server
let srv = dgram.createSocket('udp4');
srv.bind(41234, bsrv => {
  bsrv.on('message', function(msg, info) {
    // echo 1
    srv.send('echo1: '+msg, info.port, info.host);
    // echo 2 // TBD: using setTimeout() to separate the message packets
    setTimeout(() => srv.send('echo2: '+msg, info.port, info.host));
  });
});

// client
let sckt = dgram.createSocket('udp4');
sckt.on('message', function(msg, info) {
  console.log('c:message', msg, info.host, info.port);
});
sckt.send('Espruino UDP Message!', 41234, '127.0.0.1');
```

**Issues**

Messages greater than net->chunkSize seem to sometimes freeze the whole esp8266 board. This could be because of heap shortage (wasn't able to verify)
- [x] Drop messages bigger than net->chunkSize (536/2 - quite small, many osx Bonjour/mDNS messages are way bigger).

**Cleanup**
- [x] Working test_dgram_socket.js test
- [ ] Fix cross-layer interfacing and avoid hacks
- [ ] Add property name constants ("receiveData", "multicastGroup", ...) similarly to e.g. HTTP_NAME_RECEIVE_DATA
- [ ] Add doc comments to the added function parameters in network.h/c files

## Phase 2

Separating send message packets (separate pull request).

- [ ] Combine the socketserver:receiveInfo/receiveData, create a message data object {data, host, port} and pass to clientRequestWrite
- [ ] Adapt to make it send every send() call separately, not concatenating to a stream (pushData)

```js
// server
let srv = dgram.createSocket('udp4');
srv.bind(41234, bsrv => {
  bsrv.on('message', function(msg, info) {
    // echo 1
    bsrv.send('echo1: '+msg, info.port, info.host);
    // echo 2 (separate message/packet)
    bsrv.send('echo2: '+msg, info.port, info.host);
  });
});
```

**Comment by wilberforce** [comment]
@opichals 

I'm interested in following as we'll need to bring the code into the esp32 branch. The esp32 network code is cloned off the Linux base, so what every is working for Linux code be ported...

**Comment by opichals** [comment]
I assume the ESP32 related changes are way more complex so I would wait for it to be merged to master and I will rebase on top. What do you think?

**Comment by wilberforce** [comment]
@opichals 
Actually the esp32 network code is very similar to the Linux network code, so it should be a simple update.

**Comment by opichals** [comment]
For UDP there are updates to the JsNetwork interface which applies and have to be adjusted/synced for all boards netowrk stacks. My hunch is to leave this and add UDP support after the ESP32 stuff is merged.

**Comment by hungryforcodes** [comment]
Was there any updates on this by the way? I'm curious about some of the new things this might offer, including mDNS.

**Comment by opichals** [comment]
@hungryforcodes I am struggling to understand the Espruino's networking stack in detail as the changes affect all boards. Unfortunately I wasn't able to work on this recently.

On the positive side I got it working with some limitations including a basic mDNS.js responder (Linux, ESP8266 so far). The mDNS support could prove to be quite limited though due to the small amount of RAM available.

**Comment by wilberforce** [comment]
The esp32 branch has been merged into mainstream, and the network code was cloned from Linux so should be easy to merge. There is more memory on this board so you would not have the same memory limitations as the esp8266

**Comment by hungryforcodes** [comment]
@opichals Thanks for the update :) 

@wilberforce Yes we understand your position on the ESP32 :)

**Comment by gfwilliams** [comment]
I think this is probably closable now?

**Comment by opichals** [comment]
Sounds all right, I have my minor TODOs elsewhere.
